import os
import warnings
from pathlib import Path

import bokeh.embed
import numpy as np
import pandas as pd
from bokeh.models import HoverTool, LogColorMapper

from pydatalab.blocks.base import DataBlock
from pydatalab.bokeh_plots import DATALAB_BOKEH_THEME, selectable_axes_plot
from pydatalab.file_utils import get_file_info_by_id


class FTIRBlock(DataBlock):
    accepted_file_extensions: tuple[str, ...] = (".asp", ".txt")
    blocktype = "ftir"
    name = "FTIR"
    description = (
        "This block can plot FTIR data from .asp files generated by an Agilent Spectrometer"
    )

    @property
    def plot_functions(self):
        return (self.generate_ftir_plot,)

    @classmethod
    def parse_ftir_asp(cls, filename: Path) -> pd.DataFrame:
        """Parses .asp FTIR data generated by an Agilent Spectrometer

        The file consists of a header with the number of points, the start and end wavenumber, a few lines of metadata,
        and then the absorbance data. This function reads the file, extracts the absorbance data, and returns it as a
        pandas DataFrame.

        Args:
            filename: Path to the .asp file

        Returns:
            FTIR dataframe with columns "Wavenumber (cm⁻¹)" and "Absorbance (%)".
        """

        ftir = pd.read_csv(filename, header=None)
        number_of_points = int(ftir[0].iloc[0])
        start_wavenumber = ftir[0].iloc[1]
        end_wavenumber = ftir[0].iloc[2]
        x_range = np.linspace(start_wavenumber, end_wavenumber, number_of_points)
        y = ftir[0].iloc[-number_of_points:]
        return pd.DataFrame.from_dict({"Wavenumber (cm⁻¹)": x_range, "Absorbance (%)": 100 * y})

    @classmethod
    def parse_ftir_txt(cls, filename: Path) -> pd.DataFrame:
        """Parses .txt FTIR data generated by a Shimadzu IR Tracer-100 FT-IR spectrophotometer

        The file consists of a header with metadata: a title, data type, x units and y units,
        and then the IR data
        This function reads the file and extracts the data as a pandas DataFrame, and the x units and y units as strings.
        This function does not read the original .ispd file generated by the spectrometer

        Args:
            filename: Path to the .txt file

        Returns:
            FTIR dataframe with columns "Wavenumber (cm⁻¹)" and "Absorbance (%)".
        """
        with open(filename) as f:
            alldata = f.readlines()

        title = alldata[0].split("=")[1].strip()

        data_type = alldata[1].split("=")[1].strip()
        if data_type != "INFRARED SPECTRUM":
            warnings.warn(
                f"Unexpected data type {data_type} in FTIR .txt file -- labels may be incorrect"
            )
        x_unit = alldata[2].split("=")[1].strip()
        if x_unit != "1/CM":
            warnings.warn(
                f"Unexpected unit {x_unit} for wavenumber in FTIR .txt file -- labels may be incorrect"
            )
        y_unit = alldata[3].split("=")[1].strip()
        if y_unit != "%T":
            warnings.warn(
                f"Unexpected unit {y_unit} for absorbance in FTIR .txt file -- labels may be incorrect"
            )
        data = alldata[4:]
        x = [float(line.split()[0]) for line in data]
        y = [float(line.split()[1]) for line in data]
        ftir = pd.DataFrame.from_dict({"Wavenumber (cm⁻¹)": x, "Absorbance (%)": y})
        ftir.attrs["title"] = title
        return ftir

    @staticmethod
    def _format_ftir_plot(ftir_data: pd.DataFrame) -> bokeh.layouts.layout:
        """Formats FTIR data for plotting in Bokeh, inverted x-axis with a buffer of 50 cm^-1 on either side

        Args:
            ftir_data: FTIR dataframe with columns "Wavenumber (cm⁻¹)" and "Absorbance (%)"

        Returns:
            bokeh.layouts.layout: Bokeh layout with FTIR data plotted
        """
        layout = selectable_axes_plot(
            ftir_data,
            x_options=["Wavenumber (cm⁻¹)"],
            y_options=["Absorbance (%)"],
            x_range=(
                ftir_data["Wavenumber (cm⁻¹)"].max() + 50,
                ftir_data["Wavenumber (cm⁻¹)"].min() - 50,
            ),
            color_mapper=LogColorMapper("Cividis256"),
            plot_points=False,
            plot_line=True,
            tools=HoverTool(
                tooltips=[
                    ("Wavenumber", "@{Wavenumber (cm⁻¹)}{0.00} cm⁻¹"),
                    ("Absorbance", "@{Absorbance (%)}{0.0000}%"),
                ],  # Display x and y values to specified decimal places
                mode="vline",  # Ensures hover follows the x-axis
            ),
        )

        return layout

    def generate_ftir_plot(self):
        file_info = None
        ftir_data = None

        if "file_id" not in self.data:
            return

        file_info = get_file_info_by_id(self.data["file_id"], update_if_live=True)
        ext = os.path.splitext(file_info["location"].split("/")[-1])[-1].lower()
        if ext not in self.accepted_file_extensions:
            warnings.warn(
                f"Unsupported file extension (must be one of {self.accepted_file_extensions}, not {ext})"
            )
            return
        elif ext == ".asp":
            ftir_data = self.parse_ftir_asp(Path(file_info["location"]))
        elif ext == ".txt":
            ftir_data = self.parse_ftir_txt(Path(file_info["location"]))

        if ftir_data is not None:
            layout = self._format_ftir_plot(ftir_data)
            self.data["bokeh_plot_data"] = bokeh.embed.json_item(layout, theme=DATALAB_BOKEH_THEME)
