comment:
  layout: "diff, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
github_checks:
  annotations: false
