version: 2

formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - cd pydatalab && uv sync --all-extras --dev
    - cd pydatalab && uv pip install .
    - cd pydatalab && .venv/bin/mkdocs build --site-dir $READTHEDOCS_OUTPUT/html
