site_name: pydatalab
site_description: Documentation for pydatalab

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    - scheme: default
      primary: amber
      accent: brown
  font:
    text: Source Sans Pro

repo_name: the-grey-group/datalabvue
repo_url: https://github.com/the-grey-group/datalabvue

docs_dir: "pydatalab/docs"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/the-grey-group

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      # Allows mermaid code blocks to be rendered via mermaid.js
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.snippets
  - toc:
      permalink: true

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: true
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_source: true
            show_bases: true
            group_by_category: true
            heading_level: 2
            members_order: "source"
            members: true
            inherited_members: true
            docstring_style: google
            enable_inventory: false
            filters:
              - "!^_[^_]"
              - "!__json_encoder__$"
              - "!__all__$"
              - "!__config__$"
              - "!ValidatorResults$"
              - "!Config"
  - awesome-pages
  - autorefs

watch:
  - pydatalab
