import os
from pathlib import Path

import bokeh.embed
import pandas as pd
from bokeh.models import HoverTool
from galvani import MPRfile

from pydatalab.blocks.base import DataBlock
from pydatalab.bokeh_plots import DATALAB_BOKEH_THEME, selectable_axes_plot
from pydatalab.file_utils import get_file_info_by_id
from pydatalab.logger import LOGGER


class CVBlock(DataBlock):
    accepted_file_extensions: tuple[str, ...] = (".mpr",)
    blocktype = "cv"
    name = "Cyclic Voltammetry"
    description = "This block can plot CV data from .mpr files generated by a biologic potentiostat"

    @property
    def plot_functions(self):
        return (self.generate_cv_plot,)

    @classmethod
    def parse_cv_mpr(cls, filename: Path) -> dict[str, pd.DataFrame]:
        """Parses .mpr CV data generated by a biologic potentiostat.

        Returns a dict of per-cycle DataFrames keyed by "Cycle N", so that
        selectable_axes_plot can assign each cycle a distinct color.

        Args:
            filename: Path to the .mpr file

        Returns:
            Dict mapping cycle label to DataFrame with columns "Potential (V)" and "Current (mA)".
        """
        df = pd.DataFrame(MPRfile(filename).data)
        base = pd.DataFrame(
            {
                "Potential (V)": df["Ewe/V"],
                "Current (mA)": df["<I>/mA"],
                "Cycle": df["cycle number"].astype(int),
            }
        )
        return {f"Cycle {c}": grp.reset_index(drop=True) for c, grp in base.groupby("Cycle")}

    def generate_cv_plot(self):
        if "file_id" not in self.data:
            return

        file_info = get_file_info_by_id(self.data["file_id"], update_if_live=True)
        ext = os.path.splitext(file_info["location"].split("/")[-1])[-1].lower()
        if ext not in self.accepted_file_extensions:
            LOGGER.warning(
                "Unsupported file extension (must be one of %s, not %s)",
                self.accepted_file_extensions,
                ext,
            )
            return

        cv_data = self.parse_cv_mpr(file_info["location"])

        n_cycles = len(cv_data)
        hover = HoverTool(
            tooltips=[
                ("Potential", "@{Potential (V)}{0.00} V"),
                ("Current", "@{Current (mA)}{0.0000} mA"),
                ("Cycle", "@{Cycle}"),
            ],
            mode="mouse",
        )

        cycle_numbers = [df["Cycle"].iloc[0] for df in cv_data.values()]

        layout = selectable_axes_plot(
            cv_data,
            x_options=["Potential (V)"],
            y_options=["Current (mA)"],
            series_color_values=cycle_numbers if n_cycles > 8 else None,
            series_color_label="Cycle" if n_cycles > 8 else None,
            plot_points=False,
            plot_line=True,
            use_unique_labels=False,
            tools=hover,
        )

        self.data["bokeh_plot_data"] = bokeh.embed.json_item(layout, theme=DATALAB_BOKEH_THEME)
