from io import StringIO
from pathlib import Path

import numpy as np
import pandas as pd
from galvani import MPRfile


def parse_chi_cv_txt(filename: Path) -> pd.DataFrame:
    """Parse a CV .txt file exported by a CH Instruments potentiostat.

    The file has a text header followed by two-column CSV data under the
    header "Potential/V, Current/A". Cycle numbers are inferred from
    direction reversals in the potential sweep.

    Args:
        filename: Path to the .txt file.

    Returns:
        DataFrame with columns "Potential (V)", "Current (mA)", and "Cycle".

    Raises:
        RuntimeError: If the data section cannot be found or parsed.
    """
    text = Path(filename).read_text()

    marker = "Potential/V, Current/A"
    idx = text.find(marker)
    if idx == -1:
        raise RuntimeError(f"Could not find data header '{marker}' in {filename}")

    data_text = text[idx + len(marker) :]

    try:
        df = pd.read_csv(
            StringIO(data_text),
            names=["Potential (V)", "Current (A)"],
            skip_blank_lines=True,
        )
    except Exception as exc:
        raise RuntimeError(f"Failed to parse CV data from {filename}: {exc}") from exc

    if df.empty:
        raise RuntimeError(f"No data found in {filename}")

    df["Current (mA)"] = df["Current (A)"] * 1000
    df = df.drop(columns=["Current (A)"])
    half_cycles = _infer_half_cycles(df["Potential (V)"].to_numpy())
    df["Cycle"] = half_cycles // 2 + 1

    return df


def _infer_half_cycles(potential: np.ndarray) -> np.ndarray:
    """Assign a half-cycle number to each point based on potential sweep direction.

    Each continuous sweep in one direction (up or down) is one half-cycle.
    Direction reversals are detected from sign changes in the diff of the potential.

    Args:
        potential: 1-D array of potential values in sweep order.

    Returns:
        Integer array of the same length with half-cycle numbers starting at 0.
    """
    direction = np.sign(np.diff(potential))

    # Back-fill leading zeros so an initial hold doesn't look like a reversal
    first_nonzero = next((i for i, v in enumerate(direction) if v != 0), None)
    if first_nonzero is not None and first_nonzero > 0:
        direction[:first_nonzero] = direction[first_nonzero]

    # Forward-fill through any flat regions (zero diff)
    for i in range(1, len(direction)):
        if direction[i] == 0:
            direction[i] = direction[i - 1]

    # Reversals occur where consecutive directions differ
    reversals = np.where(np.diff(direction) != 0)[0] + 1  # +1 to index into original array

    half_cycle = np.zeros(len(potential), dtype=int)
    for cycle_num, start in enumerate(reversals):
        half_cycle[start:] = cycle_num + 1

    return half_cycle


def parse_cv_mpr(filename: Path) -> pd.DataFrame:
    """Parses .mpr CV data generated by a biologic potentiostat.

    Returns a dataframe containing Potential (V), Current (mA), and Cycle number columns.

    Args:
        filename: Path to the .mpr file

    Returns:
        DataFrame with columns "Potential (V)", "Current (mA)", and "Cycle".

    Raises:
        RuntimeError: If the file is missing required columns.
    """

    required_columns = {"Ewe/V", "<I>/mA", "cycle number"}
    df = pd.DataFrame(MPRfile(str(filename)).data)
    if not required_columns.issubset(df.columns):
        raise RuntimeError(
            f"Missing required columns in {filename}: expected {required_columns}, got {set(df.columns)}"
        )

    base = pd.DataFrame(
        {
            "Potential (V)": df["Ewe/V"],
            "Current (mA)": df["<I>/mA"],
            "Cycle": df["cycle number"].astype(int),
        }
    )
    return base


def _split_by_cycle(df: pd.DataFrame) -> dict[str, pd.DataFrame]:
    """Split a flat DataFrame with a 'Cycle' column into a dict of per-cycle DataFrames."""
    return {f"Cycle {c}": grp.reset_index(drop=True) for c, grp in df.groupby("Cycle")}
