import importlib.metadata
from types import ModuleType, SimpleNamespace
from typing import Literal

import tomlkit

import tasks
from pydatalab.models.samples import Sample


class MixedSolution(Sample):
    type: Literal["mixed_solutions"] = "mixed_solutions"  # type: ignore[assignment]


def _fake_plugin(tmp_path, package_name, vue_files):
    package_dir = tmp_path / package_name
    package_dir.mkdir()
    module_file = package_dir / "__init__.py"
    module_file.write_text("", encoding="utf-8")
    webapp_dir = package_dir / "webapp"
    webapp_dir.mkdir()
    for filename in vue_files:
        (webapp_dir / filename).write_text(f"<!-- {filename} -->\n", encoding="utf-8")

    module = ModuleType(package_name)
    module.__file__ = str(module_file)
    return module


def test_collect_plugin_panels_copies_helpers_and_removes_stale_output(tmp_path, monkeypatch):
    src_path = tmp_path / "webapp" / "src"
    plugins_dir = src_path / "plugins"
    plugins_dir.mkdir(parents=True)
    (plugins_dir / "index.js").write_text("// stable loader\n", encoding="utf-8")
    stale_dir = plugins_dir / "removed_plugin"
    stale_dir.mkdir()
    (stale_dir / "RemovedPanel.vue").write_text("stale", encoding="utf-8")
    (plugins_dir / "panels.generated.js").write_text("stale", encoding="utf-8")

    module = _fake_plugin(
        tmp_path,
        "example_plugin",
        ("MixedSolutionPanel.vue", "PanelHelper.vue"),
    )
    entry_points = [
        SimpleNamespace(
            name="entry_point_name_can_differ",
            value="example_plugin.models:MixedSolution",
            load=lambda: MixedSolution,
        ),
        SimpleNamespace(
            name="solutions",
            value="example_plugin.models:Solution",
            load=lambda: Sample,
        ),
    ]
    monkeypatch.setattr(importlib.metadata, "entry_points", lambda *, group: entry_points)
    monkeypatch.setattr(tasks.importlib, "import_module", lambda package_name: module)

    registered = tasks._collect_plugin_panels(src_path)

    assert registered == {
        "_mixed_solutions": "./example_plugin/MixedSolutionPanel.vue",
    }
    assert (plugins_dir / "index.js").read_text(encoding="utf-8") == "// stable loader\n"
    assert not stale_dir.exists()
    assert (plugins_dir / "example_plugin" / "MixedSolutionPanel.vue").is_file()
    assert (plugins_dir / "example_plugin" / "PanelHelper.vue").is_file()
    assert (plugins_dir / "panels.generated.js").read_text(encoding="utf-8") == (
        "// Auto-generated by `invoke dev.collect-plugin-panels` — do not edit manually.\n"
        "// Re-run plugin installation after installing or updating plugins.\n"
        "export const PLUGIN_PANELS = {\n"
        '  _mixed_solutions: () => import("./example_plugin/MixedSolutionPanel.vue"),\n'
        "};\n"
    )


def test_collect_plugin_panels_generates_empty_registry_without_plugins(tmp_path, monkeypatch):
    src_path = tmp_path / "webapp" / "src"
    plugins_dir = src_path / "plugins"
    plugins_dir.mkdir(parents=True)
    (plugins_dir / "index.js").write_text("// stable loader\n", encoding="utf-8")
    monkeypatch.setattr(importlib.metadata, "entry_points", lambda *, group: [])

    registered = tasks._collect_plugin_panels(src_path)

    assert registered == {}
    assert (
        (plugins_dir / "panels.generated.js")
        .read_text(encoding="utf-8")
        .endswith("export const PLUGIN_PANELS = {\n};\n")
    )


def _entry_points_by_group(item_types=(), blocks=()):
    groups = {"pydatalab.item_types": list(item_types), "pydatalab.apps.plugins": list(blocks)}
    return lambda *, group: groups[group]


BLOCK_PLUGIN_MANIFEST = """export default {
  apiVersion: 1,
  blocks: {
    my_block: () => import("./MyBlock.vue"),
  },
};
"""


def test_collect_plugin_panels_installs_block_plugin_manifest(tmp_path, monkeypatch):
    src_path = tmp_path / "webapp" / "src"
    plugins_dir = src_path / "plugins"
    plugins_dir.mkdir(parents=True)
    (plugins_dir / "index.js").write_text("// stable loader\n", encoding="utf-8")
    module = _fake_plugin(tmp_path, "block_plugin", ("MyBlock.vue", "BlockHelper.vue"))
    webapp_dir = tmp_path / "block_plugin" / "webapp"
    (webapp_dir / "index.js").write_text(BLOCK_PLUGIN_MANIFEST, encoding="utf-8")
    (webapp_dir / "utils.js").write_text("export const x = 1;\n", encoding="utf-8")
    block_ep = SimpleNamespace(name="my_block", value="block_plugin.blocks:MyBlock")
    monkeypatch.setattr(
        importlib.metadata, "entry_points", _entry_points_by_group(blocks=[block_ep])
    )
    monkeypatch.setattr(tasks.importlib, "import_module", lambda package_name: module)

    registered = tasks._collect_plugin_panels(src_path)

    assert registered == {}
    copied = plugins_dir / "block_plugin"
    for filename in ("MyBlock.vue", "BlockHelper.vue", "utils.js"):
        assert (copied / filename).is_file()
    assert (copied / "index.js").read_text(encoding="utf-8") == BLOCK_PLUGIN_MANIFEST
    assert (plugins_dir / "panels.generated.js").read_text(encoding="utf-8") == (
        "// Auto-generated by `invoke dev.collect-plugin-panels` — do not edit manually.\n"
        "// Re-run plugin installation after installing or updating plugins.\n"
        'import block_plugin from "./block_plugin/index.js";\n'
        "export const PLUGINS = [block_plugin];\n"
        "export const PLUGIN_PANELS = {\n"
        "};\n"
    )


def test_collect_plugin_panels_manifest_overrides_panel_convention(tmp_path, monkeypatch):
    src_path = tmp_path / "webapp" / "src"
    plugins_dir = src_path / "plugins"
    plugins_dir.mkdir(parents=True)
    manifest_module = _fake_plugin(
        tmp_path, "manifest_plugin", ("MixedSolutionPanel.vue", "index.js")
    )
    legacy_module = _fake_plugin(tmp_path, "legacy_plugin", ("MixedSolutionPanel.vue",))
    modules = {"manifest_plugin": manifest_module, "legacy_plugin": legacy_module}
    item_ep = SimpleNamespace(
        name="mixed", value="manifest_plugin.models:MixedSolution", load=lambda: MixedSolution
    )
    legacy_ep = SimpleNamespace(
        name="legacy", value="legacy_plugin.models:MixedSolution", load=lambda: MixedSolution
    )
    block_ep = SimpleNamespace(name="block", value="manifest_plugin.blocks:SomeBlock")
    monkeypatch.setattr(
        importlib.metadata,
        "entry_points",
        _entry_points_by_group(item_types=[item_ep, legacy_ep], blocks=[block_ep]),
    )
    monkeypatch.setattr(tasks.importlib, "import_module", modules.__getitem__)

    registered = tasks._collect_plugin_panels(src_path)

    # Only the manifest-less package is registered via the panel naming convention
    assert registered == {"_mixed_solutions": "./legacy_plugin/MixedSolutionPanel.vue"}
    assert (plugins_dir / "manifest_plugin" / "index.js").is_file()
    assert (plugins_dir / "manifest_plugin" / "MixedSolutionPanel.vue").is_file()
    generated = (plugins_dir / "panels.generated.js").read_text(encoding="utf-8")
    assert "export const PLUGINS = [manifest_plugin];\n" in generated


def test_collect_plugin_panels_if_available_runs_for_complete_checkout(tmp_path, monkeypatch):
    src_path = tmp_path / "webapp" / "src"
    src_path.mkdir(parents=True)
    collected = []
    monkeypatch.setattr(tasks, "_webapp_src_path", lambda: src_path)
    monkeypatch.setattr(tasks, "_collect_plugin_panels", collected.append)

    assert tasks._collect_plugin_panels_if_available() is True
    assert collected == [src_path]


def test_collect_plugin_panels_if_available_skips_server_only_install(tmp_path, monkeypatch):
    missing_src_path = tmp_path / "webapp" / "src"
    monkeypatch.setattr(tasks, "_webapp_src_path", lambda: missing_src_path)

    assert tasks._collect_plugin_panels_if_available() is False


def test_install_collects_panels_after_installation(tmp_path, monkeypatch):
    project_dir = tmp_path / "pydatalab"
    project_dir.mkdir()
    (project_dir / "tasks.py").write_text("", encoding="utf-8")
    (project_dir / "pyproject.toml").write_text(
        '[project]\nname = "test-project"\n[tool.setuptools_scm]\nroot = ".."\n[tool.uv.sources]\n',
        encoding="utf-8",
    )
    (project_dir / "uv.lock").write_text("version = 1\n", encoding="utf-8")

    commands = []
    collection_calls = []
    monkeypatch.setattr(tasks, "__file__", str(project_dir / "tasks.py"))
    monkeypatch.setattr(tasks, "PLUGINS_TOML_PATH", tmp_path / "missing-plugins.toml")
    monkeypatch.setattr(tasks.subprocess, "run", lambda command, **kwargs: commands.append(command))
    monkeypatch.setattr(
        tasks,
        "_collect_plugin_panels_if_available",
        lambda: collection_calls.append(True),
    )

    tasks.install.body(None, dev=False)

    assert collection_calls == [True]
    assert commands[-1] == ["uv", "pip", "install", "-e", "."]


def test_install_adds_plugin_sources_without_existing_sources_table(tmp_path, monkeypatch):
    project_dir = tmp_path / "pydatalab"
    project_dir.mkdir()
    (project_dir / "tasks.py").write_text("", encoding="utf-8")
    (project_dir / "pyproject.toml").write_text(
        '[project]\nname = "test-project"\n[tool.setuptools_scm]\nroot = ".."\n[tool.uv]\n',
        encoding="utf-8",
    )
    (project_dir / "uv.lock").write_text("version = 1\n", encoding="utf-8")
    plugins_toml = tmp_path / "plugins.toml"
    plugins_toml.write_text(
        'dependencies = ["my-plugin"]\n\n[tool.uv.sources]\nmy-plugin = { path = "my-plugin" }\n',
        encoding="utf-8",
    )

    monkeypatch.setattr(tasks, "__file__", str(project_dir / "tasks.py"))
    monkeypatch.setattr(tasks, "PLUGINS_TOML_PATH", plugins_toml)
    monkeypatch.setattr(tasks.subprocess, "run", lambda command, **kwargs: None)
    monkeypatch.setattr(tasks, "_collect_plugin_panels_if_available", lambda: None)

    tasks.install.body(None, dev=False)

    build_pyproject = tomlkit.loads(
        (project_dir / "build" / "pyproject.toml").read_text(encoding="utf-8")
    )
    assert build_pyproject["project"]["optional-dependencies"]["plugins"] == ["my-plugin"]
    assert build_pyproject["tool"]["uv"]["sources"]["my-plugin"]["path"] == str(
        (tmp_path / "my-plugin").resolve()
    )
