import importlib.metadata
from types import ModuleType, SimpleNamespace
from typing import Literal

import tasks
from pydatalab.models.samples import Sample


class MixedSolution(Sample):
    type: Literal["mixed_solutions"] = "mixed_solutions"  # type: ignore[assignment]


def _fake_plugin(tmp_path, package_name, vue_files):
    package_dir = tmp_path / package_name
    package_dir.mkdir()
    module_file = package_dir / "__init__.py"
    module_file.write_text("", encoding="utf-8")
    webapp_dir = package_dir / "webapp"
    webapp_dir.mkdir()
    for filename in vue_files:
        (webapp_dir / filename).write_text(f"<!-- {filename} -->\n", encoding="utf-8")

    module = ModuleType(package_name)
    module.__file__ = str(module_file)
    return module


def test_collect_plugin_panels_copies_helpers_and_removes_stale_output(tmp_path, monkeypatch):
    src_path = tmp_path / "webapp" / "src"
    plugins_dir = src_path / "plugins"
    plugins_dir.mkdir(parents=True)
    (plugins_dir / "index.js").write_text("// stable loader\n", encoding="utf-8")
    stale_dir = plugins_dir / "removed_plugin"
    stale_dir.mkdir()
    (stale_dir / "RemovedPanel.vue").write_text("stale", encoding="utf-8")
    (plugins_dir / "panels.generated.js").write_text("stale", encoding="utf-8")

    module = _fake_plugin(
        tmp_path,
        "example_plugin",
        ("MixedSolutionPanel.vue", "PanelHelper.vue"),
    )
    entry_points = [
        SimpleNamespace(
            name="entry_point_name_can_differ",
            value="example_plugin.models:MixedSolution",
            load=lambda: MixedSolution,
        ),
        SimpleNamespace(
            name="solutions",
            value="example_plugin.models:Solution",
            load=lambda: Sample,
        ),
    ]
    monkeypatch.setattr(importlib.metadata, "entry_points", lambda *, group: entry_points)
    monkeypatch.setattr(tasks.importlib, "import_module", lambda package_name: module)

    registered = tasks._collect_plugin_panels(src_path)

    assert registered == {
        "_mixed_solutions": "./example_plugin/MixedSolutionPanel.vue",
    }
    assert (plugins_dir / "index.js").read_text(encoding="utf-8") == "// stable loader\n"
    assert not stale_dir.exists()
    assert (plugins_dir / "example_plugin" / "MixedSolutionPanel.vue").is_file()
    assert (plugins_dir / "example_plugin" / "PanelHelper.vue").is_file()
    assert (plugins_dir / "panels.generated.js").read_text(encoding="utf-8") == (
        "// Auto-generated by `invoke dev.collect-plugin-panels` — do not edit manually.\n"
        "// Re-run plugin installation after installing or updating plugins.\n"
        "export const PLUGIN_PANELS = {\n"
        '  _mixed_solutions: () => import("./example_plugin/MixedSolutionPanel.vue"),\n'
        "};\n"
    )


def test_collect_plugin_panels_generates_empty_registry_without_plugins(tmp_path, monkeypatch):
    src_path = tmp_path / "webapp" / "src"
    plugins_dir = src_path / "plugins"
    plugins_dir.mkdir(parents=True)
    (plugins_dir / "index.js").write_text("// stable loader\n", encoding="utf-8")
    monkeypatch.setattr(importlib.metadata, "entry_points", lambda *, group: [])

    registered = tasks._collect_plugin_panels(src_path)

    assert registered == {}
    assert (
        (plugins_dir / "panels.generated.js")
        .read_text(encoding="utf-8")
        .endswith("export const PLUGIN_PANELS = {\n};\n")
    )


def test_collect_plugin_panels_if_available_runs_for_complete_checkout(tmp_path, monkeypatch):
    src_path = tmp_path / "webapp" / "src"
    src_path.mkdir(parents=True)
    collected = []
    monkeypatch.setattr(tasks, "_webapp_src_path", lambda: src_path)
    monkeypatch.setattr(tasks, "_collect_plugin_panels", collected.append)

    assert tasks._collect_plugin_panels_if_available() is True
    assert collected == [src_path]


def test_collect_plugin_panels_if_available_skips_server_only_install(tmp_path, monkeypatch):
    missing_src_path = tmp_path / "webapp" / "src"
    monkeypatch.setattr(tasks, "_webapp_src_path", lambda: missing_src_path)

    assert tasks._collect_plugin_panels_if_available() is False


def test_install_collects_panels_after_installation(tmp_path, monkeypatch):
    project_dir = tmp_path / "pydatalab"
    project_dir.mkdir()
    (project_dir / "tasks.py").write_text("", encoding="utf-8")
    (project_dir / "pyproject.toml").write_text(
        '[project]\nname = "test-project"\n[tool.setuptools_scm]\nroot = ".."\n[tool.uv.sources]\n',
        encoding="utf-8",
    )
    (project_dir / "uv.lock").write_text("version = 1\n", encoding="utf-8")

    commands = []
    collection_calls = []
    monkeypatch.setattr(tasks, "__file__", str(project_dir / "tasks.py"))
    monkeypatch.setattr(tasks, "PLUGINS_TOML_PATH", tmp_path / "missing-plugins.toml")
    monkeypatch.setattr(tasks.subprocess, "run", lambda command, **kwargs: commands.append(command))
    monkeypatch.setattr(
        tasks,
        "_collect_plugin_panels_if_available",
        lambda: collection_calls.append(True),
    )

    tasks.install.body(None, dev=False)

    assert collection_calls == [True]
    assert commands[-1] == ["uv", "pip", "install", "-e", "."]
