import BokehPlot from "@/components/BokehPlot.vue";

// The fixture is a `bokeh.embed.json_item()` payload generated by the Python `bokeh`
// package, containing a line figure, a `Select` widget and a `DataTable`. Rendering it
// exercises the core, widgets and tables modules of the bundled BokehJS, which used to be
// loaded as three separate scripts from cdn.bokeh.org. Assertions stay on the DOM that
// BokehJS builds around the plot: the figure itself is painted into a canvas, so its title
// and glyphs are not inspectable from here.
//
// The fixture can be regenerated with:
//
//     import json, bokeh.embed
//     from bokeh.layouts import column
//     from bokeh.models import ColumnDataSource, DataTable, Select, TableColumn
//     from bokeh.plotting import figure
//
//     src = ColumnDataSource(data=dict(x=[1, 2, 3, 4], y=[3, 1, 4, 1]))
//     p = figure(title="bundled bokehjs smoke test", width=400, height=250)
//     p.line("x", "y", source=src, line_width=2)
//     sel = Select(title="mode", value="a", options=["a", "b"])
//     table = DataTable(
//         source=src,
//         columns=[TableColumn(field="x", title="x"), TableColumn(field="y", title="y")],
//         width=400,
//         height=120,
//     )
//     print(json.dumps(bokeh.embed.json_item(column(p, sel, table))))
describe("BokehPlot", () => {
  // `cy.fixture` builds its objects in the Cypress runner's realm, but BokehJS
  // validates model properties with prototype checks that only accept objects from
  // its own realm, so the raw fixture is rejected with "given invalid value".
  // Re-parsing it with the application window's `JSON` moves it across. The app
  // itself is unaffected: it receives plot data from `fetch` in its own realm.
  beforeEach(() => {
    cy.fixture("bokeh_plot.json").then((data) => {
      cy.window().then((win) => {
        cy.wrap(win.JSON.parse(JSON.stringify(data)), { log: false }).as("bokehPlotData");
      });
    });
  });

  it("renders a plot from a Python-generated Bokeh document", function () {
    cy.mount(BokehPlot, { props: { bokehPlotData: this.bokehPlotData } });

    // The canvas backing store is only sized once BokehJS has resolved every model in
    // the document, so a non-zero width means the figure actually laid itself out. The
    // exact pixel count scales with devicePixelRatio (400 CSS px is 800 on a retina
    // display), hence the inequality rather than an exact match.
    cy.get(".bk-root canvas").should("exist");
    cy.get(".bk-root canvas")
      .first()
      .should(($canvas) => {
        expect(Number($canvas.attr("width"))).to.be.greaterThan(0);
      });
    cy.get(".alert").should("not.exist"); // the "Setting up bokeh plot..." placeholder is gone
  });

  it("renders widgets and tables from the bundled BokehJS", function () {
    cy.mount(BokehPlot, { props: { bokehPlotData: this.bokehPlotData } });

    // widgets module: the `Select` is restyled by BokehPlot once embedding succeeds
    cy.get(".bk-root select").should("exist").and("have.class", "form-control");

    // tables module: SlickGrid renders a header cell per DataTable column
    cy.get(".bk-root .slick-header-column").should("exist");
    cy.get(".bk-root .slick-column-name").should("contain.text", "x");
    cy.get(".bk-root .slick-column-name").should("contain.text", "y");
  });
});
