"""pydatalab CLI commands."""

import importlib
import shutil
from importlib.metadata import entry_points
from pathlib import Path


def collect_plugin_panels(webapp_src: str | None = None) -> None:
    """Discover Vue panel components from installed pydatalab plugins and wire them
    into the webapp.

    Scans all installed ``pydatalab.item_types`` entry points. For each plugin
    package that ships a ``webapp/<TypePanel>.vue`` file, the component is copied
    into ``webapp/src/plugins/<package_name>/`` and
    ``webapp/src/plugins/panels.generated.js`` is regenerated automatically
    (the committed ``plugins/index.js`` shim loads it when present).

    Convention: ``bath_batches`` → ``BathBatchPanel.vue``
    (snake_case type → PascalCase + "Panel")

    Usage::

        datalab-collect-plugin-panels
        datalab-collect-plugin-panels --webapp-src ./webapp/src
    """
    import argparse

    parser = argparse.ArgumentParser(
        description="Collect Vue panel components from installed pydatalab plugins."
    )
    parser.add_argument(
        "--webapp-src",
        default=webapp_src,
        help="Path to the webapp/src directory (default: auto-detected from repo root).",
    )
    args = parser.parse_args()

    src_path = Path(args.webapp_src) if args.webapp_src else _find_webapp_src()
    if not src_path or not src_path.exists():
        raise SystemExit(
            f"Could not find webapp/src at {src_path}. Pass --webapp-src <path> explicitly."
        )

    plugins_dir = src_path / "plugins"
    plugins_dir.mkdir(exist_ok=True)

    registered: dict[str, str] = {}  # type_name → import path relative to plugins/index.js

    eps = list(entry_points(group="pydatalab.item_types"))
    if not eps:
        print("No pydatalab.item_types entry points found.")

    seen_packages: set[str] = set()

    for ep in eps:
        package_name = ep.value.split(":")[0].split(".")[0]
        if package_name in seen_packages:
            continue
        seen_packages.add(package_name)

        try:
            mod = importlib.import_module(package_name)
        except ImportError:
            print(f"  [skip] Could not import {package_name}")
            continue

        webapp_dir = Path(mod.__file__).parent / "webapp"  # type: ignore[arg-type]
        if not webapp_dir.exists():
            print(f"  [skip] {package_name}: no webapp/ folder found")
            continue

        dest_pkg_dir = plugins_dir / package_name
        dest_pkg_dir.mkdir(exist_ok=True)

        for vue_file in sorted(webapp_dir.glob("*.vue")):
            dest = dest_pkg_dir / vue_file.name
            shutil.copy2(vue_file, dest)
            print(f"  Copied  {package_name}/webapp/{vue_file.name}")

    # Second pass: register types that have a matching panel
    for ep in eps:
        package_name = ep.value.split(":")[0].split(".")[0]
        panel_name = _panel_name(ep.value)
        dest_file = plugins_dir / package_name / f"{panel_name}.vue"
        if dest_file.exists():
            registered[ep.name] = f"./{package_name}/{panel_name}.vue"

    _write_index(plugins_dir / "panels.generated.js", registered)
    print(f"\nGenerated  {plugins_dir / 'panels.generated.js'}")
    if registered:
        print(f"Registered panels: {', '.join(registered.keys())}")
    else:
        print("No panels registered (no matching .vue files found).")


def _panel_name(ep_value: str) -> str:
    """``my_plugin.models:HeatTreatment`` → ``HeatTreatmentPanel``"""
    class_name = ep_value.split(":")[-1]
    return f"{class_name}Panel"


def _write_index(path: Path, registered: dict[str, str]) -> None:
    lines = [
        "// Auto-generated by `datalab-collect-plugin-panels` — do not edit manually.",
        "// Run `datalab-collect-plugin-panels` after installing or updating plugins.",
        "export const PLUGIN_PANELS = {",
    ]
    for type_name, import_path in registered.items():
        lines.append(f'  {type_name}: () => import("{import_path}"),')
    lines.append("};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _find_webapp_src() -> Path | None:
    """Walk up from cwd looking for webapp/src."""
    here = Path.cwd()
    for candidate in [here, *here.parents]:
        target = candidate / "webapp" / "src"
        if target.exists():
            return target
    return None
